stages:
  - deploy

release:
    stage: deploy
    only:
        - tags
    artifacts:
        paths:
            - Release/*.*
    before_script:
        - choco install dotnetfx
    script:
        - .\build.ps1
    tags: 
        - shared-windows
        - windows
        - windows-1809